<?php

declare(strict_types=1);

namespace App\Services;

use App\Core\Database;

/**
 * Creates a COMPLETE national town/suburb list for every state/territory from
 * database/seeds/towns_national.json (generated by tools/build-national-towns.js
 * from the open australian_postcodes dataset). Unlike the business-driven
 * national import, this guarantees towns exist everywhere — so postcode/town
 * search resolves anywhere in Australia and every town surfaces the relevant
 * regional and statewide providers.
 *
 * Fully idempotent: towns are keyed on (state_id, slug) via the table's unique
 * key and inserted with INSERT IGNORE, so existing towns (and any admin edits)
 * are never overwritten. Imported localities are created is_active = 1 but
 * noindex = 1 (the schema default) so they don't flood the sitemap.
 *
 * States/regions are ensured first from national_import.json (the canonical
 * region taxonomy), mirroring NationalImportSeeder.
 */
final class NationalTownSeeder
{
    private const CHUNK = 400;

    /** @return array<string,int|string> summary counters */
    public function seed(): array
    {
        $townsFile = base_path('database/seeds/towns_national.json');
        if (!is_file($townsFile)) {
            return ['error' => 'towns_national.json not found; run tools/build-national-towns.js first'];
        }
        $townData = json_decode((string) file_get_contents($townsFile), true);
        if (!is_array($townData) || empty($townData['towns'])) {
            return ['error' => 'invalid or empty towns_national.json'];
        }

        $regionFile = base_path('database/seeds/national_import.json');
        $regionData = is_file($regionFile)
            ? json_decode((string) file_get_contents($regionFile), true)
            : null;
        if (!is_array($regionData) || empty($regionData['states']) || empty($regionData['regions'])) {
            return ['error' => 'national_import.json (states/regions) required to map towns'];
        }

        $countryId = $this->ensureAustralia();
        $stateIds = $this->ensureStates((array) $regionData['states'], $countryId); // abbr => id
        $regionIds = $this->ensureRegions((array) $regionData['regions'], $stateIds); // canvas region id => id

        $created = 0;
        $considered = 0;
        $rows = [];
        foreach ($townData['towns'] as $t) {
            $name = trim((string) ($t['name'] ?? ''));
            $abbr = strtoupper((string) ($t['state'] ?? ''));
            $regionSlug = (string) ($t['region'] ?? '');
            if ($name === '' || !isset($stateIds[$abbr])) {
                continue;
            }
            $considered++;
            $rows[] = [
                $stateIds[$abbr],
                $regionIds[$regionSlug] ?? null,
                $name,
                str_slug($name),
                ($t['pc'] ?? null) !== null && (string) $t['pc'] !== '' ? (string) $t['pc'] : null,
                isset($t['lat']) ? (float) $t['lat'] : null,
                isset($t['lng']) ? (float) $t['lng'] : null,
            ];
            if (count($rows) >= self::CHUNK) {
                $created += $this->insertChunk($rows);
                $rows = [];
            }
        }
        if ($rows !== []) {
            $created += $this->insertChunk($rows);
        }

        return [
            'considered' => $considered,
            'created'    => $created,
            'states'     => count($stateIds),
            'regions'    => count($regionIds),
        ];
    }

    /**
     * Bulk INSERT IGNORE a batch of towns. Returns the number of rows actually
     * created (existing (state,slug) rows are ignored).
     *
     * @param array<int,array{0:int,1:?int,2:string,3:string,4:?string,5:?float,6:?float}> $rows
     */
    private function insertChunk(array $rows): int
    {
        $placeholders = [];
        $params = [];
        foreach ($rows as $r) {
            $placeholders[] = '(?, ?, ?, ?, ?, ?, ?, 1, 0, 1, NOW(), NOW())';
            array_push($params, $r[0], $r[1], $r[2], $r[3], $r[4], $r[5], $r[6]);
        }

        return Database::query(
            'INSERT IGNORE INTO towns (state_id, region_id, name, slug, primary_postcode, latitude, longitude, '
            . 'is_active, is_launch_town, noindex, created_at, updated_at) VALUES '
            . implode(', ', $placeholders),
            $params
        )->rowCount();
    }

    // ---- locations (mirrors NationalImportSeeder) --------------------------

    private function ensureAustralia(): int
    {
        Database::query(
            'INSERT IGNORE INTO countries (name, slug, iso_code, is_active, created_at, updated_at) VALUES (?, ?, ?, 1, NOW(), NOW())',
            ['Australia', 'australia', 'AU']
        );
        return (int) Database::scalar('SELECT id FROM countries WHERE slug = ?', ['australia']);
    }

    /**
     * @param array<int,array<string,mixed>> $states
     * @return array<string,int> abbreviation => state id
     */
    private function ensureStates(array $states, int $countryId): array
    {
        $map = [];
        foreach ($states as $s) {
            $abbr = (string) $s['abbr'];
            $slug = strtolower($abbr);
            Database::query(
                'INSERT IGNORE INTO states (country_id, name, slug, abbreviation, is_active, created_at, updated_at) '
                . 'VALUES (?, ?, ?, ?, 1, NOW(), NOW())',
                [$countryId, (string) $s['name'], $slug, $abbr]
            );
            $map[$abbr] = (int) Database::scalar('SELECT id FROM states WHERE slug = ?', [$slug]);
        }
        return $map;
    }

    /**
     * @param array<int,array<string,mixed>> $regions
     * @param array<string,int>              $stateIds
     * @return array<string,int> canvas region id => region id
     */
    private function ensureRegions(array $regions, array $stateIds): array
    {
        $map = [];
        foreach ($regions as $r) {
            $stateId = $stateIds[(string) $r['state']] ?? 0;
            if ($stateId === 0) {
                continue;
            }
            $slug = str_slug((string) $r['label']);
            Database::query(
                'INSERT IGNORE INTO regions (state_id, name, slug, is_active, created_at, updated_at) VALUES (?, ?, ?, 1, NOW(), NOW())',
                [$stateId, (string) $r['label'], $slug]
            );
            $map[(string) $r['id']] = (int) Database::scalar(
                'SELECT id FROM regions WHERE state_id = ? AND slug = ?',
                [$stateId, $slug]
            );
        }
        return $map;
    }
}
