<?php

declare(strict_types=1);

namespace App\Services;

use App\Core\Database;

/**
 * Imports the researched, public-source business list (database/seeds/
 * national_import.json, generated by tools/extract-canvas.js) into the live
 * schema as clearly-marked **unclaimed** directory listings, creating any
 * missing states, regions and towns along the way.
 *
 * Fully idempotent: providers are keyed on their slug, locations on their
 * (state, slug), and join rows use INSERT IGNORE / existence checks, so running
 * it again only fills gaps. Listings are flagged is_unclaimed = 1 / is_verified
 * = 0 and only expose contact details the business already publishes.
 */
final class NationalImportSeeder
{
    /** @var array<string,array<string,array<string,mixed>>> state abbr => town name => {pc,lat,lng} */
    private array $townDetails = [];

    /**
     * Trade bucket => the service that is a DIRECT match for that trade (the
     * business's headline service).
     */
    private const TRADE_PRIMARY = [
        'caravan'    => 'General caravan repairs',
        'autoelec'   => '12-volt electrical',
        'mechanical' => 'Mechanical repairs',
        'trailer'    => 'Trailer and engineering',
        'plumber'    => 'Plumbing and water leaks',
        'gasfitter'  => 'Gas appliance servicing',
        'roadside'   => 'Roadside assistance',
        'roadworthy' => 'Roadworthy inspection',
    ];

    /**
     * Trade bucket => services that the trade plausibly covers and is therefore a
     * POSSIBLE match for (shown publicly as "may offer this service"). Kept
     * conservative to what each trade genuinely handles in the caravan/RV world.
     *
     * @var array<string,array<int,string>>
     */
    private const TRADE_RELATED = [
        'caravan' => [
            'Plumbing and water leaks', 'Hot water systems', 'Toilets', 'Brakes and bearings',
            'Suspension', 'Tyres and wheels', 'Structural repairs', 'Fibreglass repairs',
            'Awning repairs', 'Roof leaks', 'Appliance repairs', 'Gas appliance servicing',
            'Refrigeration', 'Air conditioning', '12-volt electrical', 'Solar and batteries',
            'DC-DC charging', 'Inverters', 'Starlink and communications',
            'Insurance repairs', 'Pre-trip inspection', 'General servicing',
        ],
        'autoelec' => [
            '240-volt electrical', 'Solar and batteries', 'DC-DC charging', 'Inverters',
            'Refrigeration', 'Air conditioning', 'Appliance repairs', 'Starlink and communications',
            'Pre-trip inspection',
        ],
        'mechanical' => [
            'General servicing', 'Brakes and bearings', 'Suspension', 'Tyres and wheels',
            'Air conditioning', 'Pre-trip inspection',
        ],
        'trailer' => [
            'Brakes and bearings', 'Suspension', 'Tyres and wheels', 'Structural repairs',
            'General servicing', 'Pre-trip inspection',
        ],
        'plumber' => [
            'Hot water systems', 'Toilets', 'Gas appliance servicing', 'Roof leaks',
            'Refrigeration', 'Pre-trip inspection',
        ],
        'gasfitter' => [
            'Hot water systems', 'Plumbing and water leaks', 'Toilets', 'Appliance repairs',
            'Refrigeration', 'Air conditioning', 'Pre-trip inspection',
        ],
        // Roadside clubs are a distinct service (no plausible repair "possible
        // matches"); a roadworthy inspector commonly also does a pre-trip check.
        'roadside' => [],
        'roadworthy' => [
            'Pre-trip inspection',
        ],
    ];

    /** @return array<string,int|string> summary counters */
    public function seed(): array
    {
        $data = $this->loadNational();
        if (isset($data['error'])) {
            return $data;
        }

        [$regionIds, $regionState, $stateIds, $categoryIds] = $this->prepare($data);

        $counters = $this->newCounters($stateIds, $regionIds);
        $townCache = [];
        foreach ($data['businesses'] as $b) {
            $this->processBusiness((array) $b, $regionIds, $regionState, $stateIds, $categoryIds, $townCache, $counters);
        }

        return $counters;
    }

    /**
     * Import a batch of the free OpenStreetMap business set
     * (database/seeds/businesses_osm.json, generated by tools/osm-import.js)
     * through the exact same unclaimed-listing path as the researched import.
     *
     * Batched (offset/limit) so the large national set can be imported from the
     * browser without hitting PHP/web timeouts; the caller loops until
     * `next` is -1. Idempotent: listings are keyed on their OSM-derived slug.
     *
     * @return array<string,int|string> summary counters incl. total/offset/processed/next
     */
    public function seedOsm(int $offset = 0, int $limit = 400): array
    {
        $data = $this->loadNational();
        if (isset($data['error'])) {
            return $data;
        }
        [$regionIds, $regionState, $stateIds, $categoryIds] = $this->prepare($data);

        $file = \App\Services\OsmRefreshService::resolveSeedPath();
        if ($file === null) {
            return ['error' => 'businesses_osm.json not found; use Admin → Maintenance → Refresh from OpenStreetMap'];
        }
        $osm = json_decode((string) file_get_contents($file), true);
        $businesses = is_array($osm) ? (array) ($osm['businesses'] ?? []) : [];
        $total = count($businesses);
        if ($total === 0) {
            return ['error' => 'businesses_osm.json is empty'];
        }

        $offset = max(0, $offset);
        $limit = max(1, $limit);
        $slice = array_slice($businesses, $offset, $limit);

        $counters = $this->newCounters($stateIds, $regionIds);
        $townCache = [];
        foreach ($slice as $b) {
            $this->processBusiness((array) $b, $regionIds, $regionState, $stateIds, $categoryIds, $townCache, $counters);
        }

        $processed = count($slice);
        $counters['total'] = $total;
        $counters['offset'] = $offset;
        $counters['processed'] = $processed;
        $counters['next'] = ($offset + $processed < $total) ? $offset + $processed : -1;
        return $counters;
    }

    /**
     * Import the locality→provider research matrix (split seed files under
     * database/seeds/, generated by tools/excel-locality-import.py) as unclaimed
     * listings with per-town service areas. Batched for browser import.
     *
     * @return array<string,int|string>
     */
    public function seedLocality(int $offset = 0, int $limit = 500): array
    {
        $data = $this->loadNational();
        if (isset($data['error'])) {
            return $data;
        }
        [$regionIds, $regionState, $stateIds, $categoryIds] = $this->prepare($data);

        $businesses = self::loadLocalityBusinesses();
        if ($businesses === []) {
            return ['error' => 'Locality seed not found; run tools/excel-locality-import.py first'];
        }

        $covFile = base_path('database/seeds/businesses_locality_coverage.jsonl');
        if (!is_file($covFile)) {
            return ['error' => 'businesses_locality_coverage.jsonl not found; run tools/excel-locality-import.py first'];
        }

        $total = self::localityCoverageCount();
        if ($total === 0) {
            return ['error' => 'Locality coverage seed is empty or invalid'];
        }

        $offset = max(0, $offset);
        $limit = max(1, $limit);
        $slice = self::readLocalityCoverageSlice($covFile, $offset, $limit);

        $counters = $this->newCounters($stateIds, $regionIds);
        $counters['areas'] = 0;
        $townCache = [];
        foreach ($slice as $cov) {
            $bid = (string) (($cov['bid'] ?? '') ?: '');
            if ($bid === '' || !isset($businesses[$bid])) {
                $counters['skipped']++;
                continue;
            }
            $this->processLocalityCoverage((array) $cov, (array) $businesses[$bid], $regionIds, $regionState, $stateIds, $categoryIds, $townCache, $counters);
        }

        $processed = count($slice);
        $counters['total'] = $total;
        $counters['offset'] = $offset;
        $counters['processed'] = $processed;
        $counters['next'] = ($offset + $processed < $total) ? $offset + $processed : -1;
        return $counters;
    }

    /** Coverage assignment count from the lightweight meta file or JSONL line count. */
    public static function localityCoverageCount(): int
    {
        $metaFile = base_path('database/seeds/businesses_locality.meta.json');
        if (is_file($metaFile)) {
            $meta = json_decode((string) file_get_contents($metaFile), true);
            if (is_array($meta)) {
                return max(0, (int) ($meta['coverage_count'] ?? 0));
            }
        }

        $covFile = base_path('database/seeds/businesses_locality_coverage.jsonl');
        return is_file($covFile) ? self::countJsonlLines($covFile) : 0;
    }

    /** @return array<string,array<string,mixed>> */
    private static function loadLocalityBusinesses(): array
    {
        $bizFile = base_path('database/seeds/businesses_locality_businesses.json');
        if (!is_file($bizFile)) {
            return [];
        }
        $decoded = json_decode((string) file_get_contents($bizFile), true);
        return is_array($decoded) ? $decoded : [];
    }

    /**
     * @return array<int,array<string,mixed>>
     */
    private static function readLocalityCoverageSlice(string $jsonlFile, int $offset, int $limit): array
    {
        $slice = [];
        $fh = fopen($jsonlFile, 'rb');
        if ($fh === false) {
            return [];
        }

        $index = 0;
        $taken = 0;
        while (($line = fgets($fh)) !== false) {
            if ($index >= $offset) {
                $row = json_decode(trim($line), true);
                if (is_array($row)) {
                    $slice[] = $row;
                    $taken++;
                    if ($taken >= $limit) {
                        break;
                    }
                }
            }
            $index++;
        }
        fclose($fh);

        return $slice;
    }

    private static function countJsonlLines(string $file): int
    {
        $count = 0;
        $fh = fopen($file, 'rb');
        if ($fh === false) {
            return 0;
        }
        while (fgets($fh) !== false) {
            $count++;
        }
        fclose($fh);

        return $count;
    }

    /** @return array{0:array<string,int>,1:array<string,string>,2:array<string,int>,3:array<string,int>} */
    private function prepare(array $data): array
    {
        $countryId = $this->ensureAustralia();
        $stateIds = $this->ensureStates((array) $data['states'], $countryId);
        $regionIds = $this->ensureRegions((array) $data['regions'], $stateIds);

        $regionState = [];
        foreach ($data['regions'] as $r) {
            $regionState[(string) $r['id']] = (string) $r['state'];
        }
        $this->ensureCategoriesExist();
        $categoryIds = $this->categoryMap();
        $this->townDetails = $this->loadTownDetails();

        return [$regionIds, $regionState, $stateIds, $categoryIds];
    }

    /**
     * Loads and validates national_import.json (the source of states, regions and
     * the researched businesses). Returns ['error' => ...] on failure.
     *
     * @return array<string,mixed>
     */
    private function loadNational(): array
    {
        $file = base_path('database/seeds/national_import.json');
        if (!is_file($file)) {
            return ['error' => 'national_import.json not found; run tools/extract-canvas.js first'];
        }
        $data = json_decode((string) file_get_contents($file), true);
        if (!is_array($data) || empty($data['businesses']) || empty($data['regions'])) {
            return ['error' => 'invalid or empty national_import.json'];
        }
        return $data;
    }

    /**
     * @param array<string,int> $stateIds
     * @param array<string,int> $regionIds
     * @return array<string,int>
     */
    private function newCounters(array $stateIds, array $regionIds): array
    {
        return ['states' => count($stateIds), 'regions' => count($regionIds), 'towns' => 0, 'towns_enriched' => 0, 'providers' => 0, 'providers_enriched' => 0, 'skipped' => 0];
    }

    /**
     * Inserts/enriches one business (and its town, services and service areas).
     * Shared by the researched import and the OpenStreetMap import.
     *
     * @param array<string,mixed> $b
     * @param array<string,int>    $regionIds
     * @param array<string,string> $regionState
     * @param array<string,int>    $stateIds
     * @param array<string,int>    $categoryIds
     * @param array<string,int>    $townCache
     * @param array<string,int>    $counters
     */
    private function processBusiness(array $b, array $regionIds, array $regionState, array $stateIds, array $categoryIds, array &$townCache, array &$counters): void
    {
        $regionCanvasId = (string) ($b['region'] ?? '');
        if (!isset($regionIds[$regionCanvasId])) {
            $counters['skipped']++;
            return;
        }
        $regionId = $regionIds[$regionCanvasId];
        $stateAbbr = $regionState[$regionCanvasId] ?? '';
        $stateId = $stateIds[$stateAbbr] ?? 0;
        if ($stateId === 0) {
            $counters['skipped']++;
            return;
        }

        $townId = $this->ensureTown(trim((string) ($b['town'] ?? '')), $stateId, $stateAbbr, $regionId, $townCache, $counters);

        $slug = $this->providerSlug((string) ($b['id'] ?? ''), (string) ($b['name'] ?? ''));
        $providerId = (int) Database::scalar('SELECT id FROM providers WHERE slug = ?', [$slug]);
        if ($providerId === 0) {
            $providerId = $this->insertProvider($b, $slug, $townId, $regionId);
            $counters['providers']++;
        } elseif ($providerId > 0) {
            // Existing unclaimed listing: backfill any contact/address detail
            // that is still missing so older imports gain the new fields.
            if ($this->enrichProvider($providerId, $b)) {
                $counters['providers_enriched']++;
            }
        }

        if ($providerId > 0) {
            $cats = (array) ($b['cats'] ?? []);
            $this->ensureServices($providerId, $cats, $categoryIds);
            if ($townId > 0) {
                $this->ensureTownArea($providerId, $townId);
            }
            // Roadside assistance is genuinely statewide, so give those listings a
            // state-wide service area (honoured by Provider::inTown / forCategory)
            // instead of being pinned to one town.
            if (in_array('roadside', $cats, true) && $stateId > 0) {
                $this->ensureStateArea($providerId, $stateId);
            }
        }
    }

    // ---- locations ---------------------------------------------------------

    private function ensureAustralia(): int
    {
        Database::query(
            'INSERT IGNORE INTO countries (name, slug, iso_code, is_active, created_at, updated_at) VALUES (?, ?, ?, 1, NOW(), NOW())',
            ['Australia', 'australia', 'AU']
        );
        return (int) Database::scalar('SELECT id FROM countries WHERE slug = ?', ['australia']);
    }

    /**
     * @param array<int,array<string,mixed>> $states
     * @return array<string,int> abbreviation => state id
     */
    private function ensureStates(array $states, int $countryId): array
    {
        $map = [];
        foreach ($states as $s) {
            $abbr = (string) $s['abbr'];
            $slug = strtolower($abbr);
            Database::query(
                'INSERT IGNORE INTO states (country_id, name, slug, abbreviation, is_active, created_at, updated_at) '
                . 'VALUES (?, ?, ?, ?, 1, NOW(), NOW())',
                [$countryId, (string) $s['name'], $slug, $abbr]
            );
            $map[$abbr] = (int) Database::scalar('SELECT id FROM states WHERE slug = ?', [$slug]);
        }
        return $map;
    }

    /**
     * @param array<int,array<string,mixed>> $regions
     * @param array<string,int>              $stateIds
     * @return array<string,int> canvas region id => region id
     */
    private function ensureRegions(array $regions, array $stateIds): array
    {
        $map = [];
        foreach ($regions as $r) {
            $stateId = $stateIds[(string) $r['state']] ?? 0;
            if ($stateId === 0) {
                continue;
            }
            $slug = str_slug((string) $r['label']);
            Database::query(
                'INSERT IGNORE INTO regions (state_id, name, slug, is_active, created_at, updated_at) VALUES (?, ?, ?, 1, NOW(), NOW())',
                [$stateId, (string) $r['label'], $slug]
            );
            $map[(string) $r['id']] = (int) Database::scalar(
                'SELECT id FROM regions WHERE state_id = ? AND slug = ?',
                [$stateId, $slug]
            );
        }
        return $map;
    }

    /**
     * @param array<string,int> $cache
     * @param array<string,int> $counters
     */
    private function ensureTown(string $name, int $stateId, string $stateAbbr, int $regionId, array &$cache, array &$counters, ?array $coords = null): int
    {
        if ($name === '') {
            return 0;
        }
        $slug = str_slug($name);
        $key = $stateId . '|' . $slug;
        $detail = $coords ?? $this->townDetails[$stateAbbr][$name] ?? null;
        $pc = isset($detail['pc']) ? (string) $detail['pc'] : (isset($detail['postcode']) ? (string) $detail['postcode'] : null);
        $lat = isset($detail['lat']) ? (float) $detail['lat'] : null;
        $lng = isset($detail['lng']) ? (float) $detail['lng'] : null;

        if (isset($cache[$key])) {
            $id = $cache[$key];
        } else {
            $id = (int) Database::scalar('SELECT id FROM towns WHERE state_id = ? AND slug = ?', [$stateId, $slug]);
            if ($id === 0) {
                Database::query(
                    'INSERT IGNORE INTO towns (state_id, region_id, name, slug, primary_postcode, latitude, longitude, is_active, is_launch_town, noindex, created_at, updated_at) '
                    . 'VALUES (?, ?, ?, ?, ?, ?, ?, 1, 0, 1, NOW(), NOW())',
                    [$stateId, $regionId ?: null, $name, $slug, $pc, $lat, $lng]
                );
                $id = (int) Database::scalar('SELECT id FROM towns WHERE state_id = ? AND slug = ?', [$stateId, $slug]);
                if ($id > 0) {
                    $counters['towns']++;
                }
            }
            $cache[$key] = $id;
        }

        // Backfill postcode/coordinates on existing rows without overwriting any
        // values that are already present.
        if ($id > 0 && $detail !== null) {
            $affected = Database::query(
                'UPDATE towns SET '
                . "primary_postcode = COALESCE(NULLIF(primary_postcode, ''), ?), "
                . 'latitude = COALESCE(latitude, ?), '
                . 'longitude = COALESCE(longitude, ?), '
                . 'region_id = COALESCE(region_id, ?), '
                . 'updated_at = NOW() '
                . "WHERE id = ? AND (primary_postcode IS NULL OR primary_postcode = '' OR latitude IS NULL OR longitude IS NULL OR region_id IS NULL)",
                [$pc, $lat, $lng, $regionId ?: null, $id]
            )->rowCount();
            if ($affected > 0) {
                $counters['towns_enriched']++;
            }
        }

        return $id;
    }

    /**
     * One locality×role assignment from the Excel research matrix: ensure the
     * town exists (with G-NAF coordinates), create/enrich the provider, link the
     * service category, and record a town- or state-level service area.
     *
     * @param array<string,mixed> $cov
     * @param array<string,mixed> $biz
     * @param array<string,int>    $regionIds
     * @param array<string,string> $regionState
     * @param array<string,int>    $stateIds
     * @param array<string,int>    $categoryIds
     * @param array<string,int>    $townCache
     * @param array<string,int>    $counters
     */
    private function processLocalityCoverage(
        array $cov,
        array $biz,
        array $regionIds,
        array $regionState,
        array $stateIds,
        array $categoryIds,
        array &$townCache,
        array &$counters
    ): void {
        $stateAbbr = strtoupper(trim((string) ($cov['state'] ?? '')));
        $stateId = $stateIds[$stateAbbr] ?? 0;
        if ($stateId === 0) {
            $counters['skipped']++;
            return;
        }

        $regionCanvasId = trim((string) ($cov['region'] ?? ''));
        if ($regionCanvasId === '' || !isset($regionIds[$regionCanvasId])) {
            $counters['skipped']++;
            return;
        }
        $regionId = $regionIds[$regionCanvasId];

        $townName = trim((string) ($cov['town'] ?? ''));
        $coords = [
            'postcode' => $cov['postcode'] ?? null,
            'lat'      => $cov['lat'] ?? null,
            'lng'      => $cov['lng'] ?? null,
        ];
        $townId = $this->ensureTown($townName, $stateId, $stateAbbr, $regionId, $townCache, $counters, $coords);

        $baseName = trim((string) ($biz['base'] ?? $townName));
        $baseRegionId = $regionId;
        if ($baseName !== '' && $baseName !== $townName) {
            $baseRegionCanvas = $regionCanvasId;
            $baseTownId = $this->ensureTown($baseName, $stateId, $stateAbbr, $baseRegionId, $townCache, $counters);
        } else {
            $baseTownId = $townId;
        }

        $slug = $this->providerSlug((string) ($biz['id'] ?? ''), (string) ($biz['name'] ?? ''));
        $providerId = (int) Database::scalar('SELECT id FROM providers WHERE slug = ?', [$slug]);
        if ($providerId === 0) {
            $record = [
                'id'                  => (string) ($biz['id'] ?? ''),
                'name'                => (string) ($biz['name'] ?? ''),
                'phone'               => (string) ($biz['phone'] ?? ''),
                'email'               => (string) ($biz['email'] ?? ''),
                'website'             => (string) ($biz['website'] ?? ''),
                'source_url'          => (string) ($biz['source_url'] ?? ''),
                'source_type'         => 'locality',
                'coverage_confidence' => str_contains(strtolower((string) ($cov['band'] ?? '')), 'statewide') ? 'statewide' : 'curated',
                'address'             => $baseName !== '' ? $baseName : $townName,
                'services'            => 'Coverage from locality-provider research. Confirm service radius before referral.',
                'modes'               => (array) ($biz['modes'] ?? ['mobile']),
            ];
            $providerId = $this->insertProvider($record, $slug, $baseTownId, $baseRegionId);
            $counters['providers']++;
        } elseif ($providerId > 0) {
            $enrich = [
                'phone'   => (string) ($biz['phone'] ?? ''),
                'email'   => (string) ($biz['email'] ?? ''),
                'website' => (string) ($biz['website'] ?? ''),
            ];
            if ($this->enrichProvider($providerId, $enrich)) {
                $counters['providers_enriched']++;
            }
        }

        if ($providerId <= 0) {
            return;
        }

        $cat = (string) ($cov['cat'] ?? '');
        if ($cat !== '') {
            $this->ensureServices($providerId, [$cat], $categoryIds);
        }

        $band = strtolower((string) ($cov['band'] ?? ''));
        if (str_contains($band, 'statewide')) {
            $before = (int) Database::scalar(
                "SELECT COUNT(*) FROM provider_service_areas WHERE provider_id = ? AND area_type = 'state' AND state_id = ?",
                [$providerId, $stateId]
            );
            $this->ensureStateArea($providerId, $stateId);
            if ($before === 0) {
                $counters['areas']++;
            }
        } elseif ($townId > 0) {
            $before = (int) Database::scalar(
                "SELECT COUNT(*) FROM provider_service_areas WHERE provider_id = ? AND area_type = 'town' AND town_id = ?",
                [$providerId, $townId]
            );
            $this->ensureTownArea($providerId, $townId);
            if ($before === 0) {
                $counters['areas']++;
            }
        }
    }

    /** @return array<string,array<string,array<string,mixed>>> state => town name => details */
    private function loadTownDetails(): array
    {
        $file = base_path('database/seeds/town_details.json');
        if (!is_file($file)) {
            return [];
        }
        $data = json_decode((string) file_get_contents($file), true);
        if (!is_array($data)) {
            return [];
        }
        unset($data['_comment']);
        return $data;
    }

    // ---- providers ---------------------------------------------------------

    /** @param array<string,mixed> $b */
    private function insertProvider(array $b, string $slug, int $townId, int $regionId): int
    {
        $modes = (array) ($b['modes'] ?? []);
        $hasMobile = in_array('mobile', $modes, true);
        $hasWorkshop = in_array('workshop', $modes, true);
        $model = 'mobile';
        if ($hasMobile && $hasWorkshop) {
            $model = 'both';
        } elseif ($hasWorkshop) {
            $model = 'workshop';
        }

        $phone = trim((string) ($b['phone'] ?? ''));
        $website = trim((string) ($b['website'] ?? '')) ?: null;
        $email = trim((string) ($b['email'] ?? '')) ?: null;
        $address = trim((string) ($b['address'] ?? '')) ?: null;
        $desc = $this->buildDescription($b);
        $sourceUrl = trim((string) ($b['source_url'] ?? '')) ?: $website;

        // Unclaimed listings are opted OUT of automated invite emails: they are
        // public-source businesses that have not opted in, so they are never
        // auto-emailed. They remain manually invitable from the matching console,
        // and claiming the listing can flip this on.
        $sourceType = trim((string) ($b['source_type'] ?? '')) ?: null;
        if ($sourceType === null) {
            $rawId = (string) ($b['id'] ?? '');
            if (str_starts_with($rawId, 'osm-')) {
                $sourceType = 'osm';
            } elseif (isset($b['source_place_id']) || str_starts_with($rawId, 'places-')) {
                $sourceType = 'national';
            }
        }
        $confidence = trim((string) ($b['coverage_confidence'] ?? '')) ?: null;

        return Database::insert(
            'INSERT INTO providers (business_name, slug, phone, public_phone, show_public_phone, email, website, '
            . 'base_town_id, region_id, street_address, description, service_model, status, is_verified, is_unclaimed, '
            . 'auto_invite_opt_out, is_demo, plan, source_note, source_url, source_type, coverage_confidence, created_at, updated_at) '
            . "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'active', 0, 1, 1, 0, 'standard_free', ?, ?, ?, ?, NOW(), NOW())",
            [
                (string) ($b['name'] ?? 'Unnamed business'), $slug,
                $phone ?: null, $phone ?: null, $phone !== '' ? 1 : 0,
                $email, $website,
                $townId ?: null, $regionId ?: null, $address, $desc, $model,
                'Imported from public research (unclaimed listing)', $sourceUrl, $sourceType, $confidence,
            ]
        );
    }

    /**
     * The public blurb for a listing: the researched services summary plus any
     * note. The source location string is kept in the structured street_address
     * column instead of being duplicated here.
     *
     * @param array<string,mixed> $b
     */
    private function buildDescription(array $b): string
    {
        $desc = trim((string) ($b['services'] ?? ''));
        if (!empty($b['note'])) {
            $desc .= ($desc !== '' ? "\n\n" : '') . 'Note: ' . trim((string) $b['note']);
        }
        return $desc;
    }

    /**
     * Backfills contact/address detail on an already-imported unclaimed listing
     * without overwriting any value already present (claimed/managed providers
     * are never touched). Returns true if the row changed.
     *
     * @param array<string,mixed> $b
     */
    private function enrichProvider(int $providerId, array $b): bool
    {
        $phone = trim((string) ($b['phone'] ?? ''));
        $email = trim((string) ($b['email'] ?? '')) ?: null;
        $website = trim((string) ($b['website'] ?? '')) ?: null;
        $address = trim((string) ($b['address'] ?? '')) ?: null;
        $desc = $this->buildDescription($b);

        $affected = Database::query(
            'UPDATE providers SET '
            . "street_address = COALESCE(NULLIF(street_address, ''), ?), "
            . "public_phone   = COALESCE(NULLIF(public_phone, ''), ?), "
            . "phone          = COALESCE(NULLIF(phone, ''), ?), "
            . 'show_public_phone = GREATEST(show_public_phone, ?), '
            . "email          = COALESCE(NULLIF(email, ''), ?), "
            . "website        = COALESCE(NULLIF(website, ''), ?), "
            . 'description     = ?, '
            . 'updated_at = NOW() '
            . 'WHERE id = ? AND is_unclaimed = 1',
            [$address, $phone ?: null, $phone ?: null, $phone !== '' ? 1 : 0, $email, $website, $desc, $providerId]
        )->rowCount();

        return $affected > 0;
    }

    /**
     * Links a provider to its services: the trade's headline service as a DIRECT
     * match, plus every service the trade plausibly covers as a POSSIBLE match
     * (is_inferred = 1). A service is never listed as possible if it is already a
     * direct match for the same business.
     *
     * @param array<int,string> $cats
     * @param array<string,int> $categoryIds
     */
    private function ensureServices(int $providerId, array $cats, array $categoryIds): void
    {
        $direct = [];
        $possible = [];
        foreach ($cats as $cat) {
            $cat = (string) $cat;
            if (isset(self::TRADE_PRIMARY[$cat])) {
                $direct[self::TRADE_PRIMARY[$cat]] = true;
            }
            foreach (self::TRADE_RELATED[$cat] ?? [] as $name) {
                $possible[$name] = true;
            }
        }

        foreach (array_keys($direct) as $name) {
            unset($possible[$name]);
            $this->linkService($providerId, $categoryIds[$name] ?? 0, 0);
        }
        foreach (array_keys($possible) as $name) {
            $this->linkService($providerId, $categoryIds[$name] ?? 0, 1);
        }
    }

    private function linkService(int $providerId, int $categoryId, int $isInferred): void
    {
        if ($categoryId === 0) {
            return;
        }
        Database::query(
            'INSERT IGNORE INTO provider_services (provider_id, category_id, is_inferred, created_at) VALUES (?, ?, ?, NOW())',
            [$providerId, $categoryId, $isInferred]
        );
    }

    /**
     * Guarantees every service this importer can link to (each trade's headline
     * service plus its possible-match services) exists in service_categories,
     * inserting any that are missing. Lets the import add new trades (e.g.
     * roadside / roadworthy) on an already-seeded database without a full reseed.
     */
    private function ensureCategoriesExist(): void
    {
        $names = [];
        foreach (self::TRADE_PRIMARY as $name) {
            $names[$name] = true;
        }
        foreach (self::TRADE_RELATED as $list) {
            foreach ($list as $name) {
                $names[$name] = true;
            }
        }
        foreach (array_keys($names) as $name) {
            $exists = (int) Database::scalar('SELECT COUNT(*) FROM service_categories WHERE slug = ?', [str_slug($name)]);
            if ($exists === 0) {
                $next = (int) Database::scalar('SELECT COALESCE(MAX(sort_order), 0) + 10 FROM service_categories');
                Database::query(
                    'INSERT IGNORE INTO service_categories (name, slug, sort_order, is_active, created_at, updated_at) '
                    . 'VALUES (?, ?, ?, 1, NOW(), NOW())',
                    [$name, str_slug($name), $next]
                );
            }
        }
    }

    private function ensureStateArea(int $providerId, int $stateId): void
    {
        if ($stateId <= 0) {
            return;
        }
        $exists = (int) Database::scalar(
            "SELECT COUNT(*) FROM provider_service_areas WHERE provider_id = ? AND area_type = 'state' AND state_id = ?",
            [$providerId, $stateId]
        );
        if ($exists === 0) {
            Database::query(
                "INSERT INTO provider_service_areas (provider_id, area_type, state_id, label, created_at) VALUES (?, 'state', ?, 'Statewide', NOW())",
                [$providerId, $stateId]
            );
        }
    }

    private function ensureTownArea(int $providerId, int $townId): void
    {
        $exists = (int) Database::scalar(
            "SELECT COUNT(*) FROM provider_service_areas WHERE provider_id = ? AND area_type = 'town' AND town_id = ?",
            [$providerId, $townId]
        );
        if ($exists === 0) {
            Database::query(
                "INSERT INTO provider_service_areas (provider_id, area_type, town_id, created_at) VALUES (?, 'town', ?, NOW())",
                [$providerId, $townId]
            );
        }
    }

    /** @return array<string,int> category name => id */
    private function categoryMap(): array
    {
        $map = [];
        foreach (Database::select('SELECT id, name FROM service_categories') as $row) {
            $map[(string) $row['name']] = (int) $row['id'];
        }
        return $map;
    }

    private function providerSlug(string $id, string $name): string
    {
        $slug = str_slug($id !== '' ? $id : $name);
        if ($slug === '') {
            $slug = 'provider-' . substr(md5($name), 0, 8);
        }
        return substr($slug, 0, 190);
    }
}
