<?php

declare(strict_types=1);

/**
 * Default billing plans seeded into editable database tables.
 *
 * IMPORTANT: names, prices, limits and features here are only the *initial*
 * values. Administrators edit them online via billing_plans / billing_plan_*
 * tables. Business logic must NEVER hardcode these values — it asks the
 * PlanEntitlementService instead. Prices are in integer cents (AUD).
 *
 * limit_value = null means "unlimited".
 */

return [
    'plans' => [
        [
            'slug'          => 'founding_free',
            'internal_name' => 'Founding Provider',
            'public_name'   => 'Founding Provider',
            'description'   => 'Reserved for providers who join during the initial launch. Free standard profile for life with a Founding Provider badge. Agreed benefits are stored per provider and never removed by later plan edits.',
            'monthly_price_cents' => 0,
            'annual_price_cents'  => 0,
            'trial_days'    => 0,
            'display_order' => 10,
            'is_active'     => 1,
            'is_public'     => 0,
            'signup_available' => 0,
            'is_recommended' => 0,
            'terms_summary' => 'Lifetime standard-level access granted to founding providers during the free launch.',
            'limits' => [
                'maximum_active_runs'       => 5,
                'maximum_service_categories' => null,
                'maximum_service_areas'     => null,
                'maximum_provider_users'    => 1,
                'maximum_branches'          => 1,
            ],
            'features' => [
                'can_create_service_run'            => true,
                'can_view_full_matching_requests'   => true,
                'can_access_advanced_statistics'    => true,
                'can_access_demand_reports'         => false,
                'can_be_featured'                   => false,
                'can_export_data'                   => false,
                'can_use_priority_matching'         => false,
                'can_create_caravan_park_service_days' => false,
                'can_use_custom_branding'           => false,
                'can_access_api'                    => false,
            ],
        ],
        [
            'slug'          => 'free',
            'internal_name' => 'Free Provider',
            'public_name'   => 'Free',
            'description'   => 'Basic public profile with limited categories, areas and active runs. Email notifications and a basic dashboard.',
            'monthly_price_cents' => 0,
            'annual_price_cents'  => 0,
            'trial_days'    => 0,
            'display_order' => 20,
            'is_active'     => 1,
            'is_public'     => 1,
            'signup_available' => 1,
            'is_recommended' => 0,
            'terms_summary' => 'Free forever with limited capacity.',
            'limits' => [
                'maximum_active_runs'       => 1,
                'maximum_service_categories' => 3,
                'maximum_service_areas'     => 2,
                'maximum_provider_users'    => 1,
                'maximum_branches'          => 1,
            ],
            'features' => [
                'can_create_service_run'            => true,
                'can_view_full_matching_requests'   => false,
                'can_access_advanced_statistics'    => false,
                'can_access_demand_reports'         => false,
                'can_be_featured'                   => false,
                'can_export_data'                   => false,
                'can_use_priority_matching'         => false,
                'can_create_caravan_park_service_days' => false,
                'can_use_custom_branding'           => false,
                'can_access_api'                    => false,
            ],
        ],
        [
            'slug'          => 'standard',
            'internal_name' => 'Standard Provider',
            'public_name'   => 'Standard',
            'description'   => 'Expanded profile, more categories and areas, multiple active runs, full matching-request access, run-capacity tools and provider statistics.',
            'monthly_price_cents' => 4900,
            'annual_price_cents'  => 49000,
            'trial_days'    => 0,
            'display_order' => 30,
            'is_active'     => 1,
            'is_public'     => 1,
            'signup_available' => 1,
            'is_recommended' => 1,
            'terms_summary' => 'Monthly or annual. Prices are placeholders pending review.',
            'limits' => [
                'maximum_active_runs'       => 5,
                'maximum_service_categories' => 10,
                'maximum_service_areas'     => 10,
                'maximum_provider_users'    => 1,
                'maximum_branches'          => 1,
            ],
            'features' => [
                'can_create_service_run'            => true,
                'can_view_full_matching_requests'   => true,
                'can_access_advanced_statistics'    => true,
                'can_access_demand_reports'         => false,
                'can_be_featured'                   => false,
                'can_export_data'                   => false,
                'can_use_priority_matching'         => false,
                'can_create_caravan_park_service_days' => false,
                'can_use_custom_branding'           => false,
                'can_access_api'                    => false,
            ],
        ],
        [
            'slug'          => 'professional',
            'internal_name' => 'Professional Provider',
            'public_name'   => 'Professional',
            'description'   => 'Higher run limits, multiple staff accounts and branches, advanced demand reports, priority matching, featured eligibility, CSV exports and caravan-park service-day tools.',
            'monthly_price_cents' => 9900,
            'annual_price_cents'  => 99000,
            'trial_days'    => 0,
            'display_order' => 40,
            'is_active'     => 1,
            'is_public'     => 1,
            'signup_available' => 1,
            'is_recommended' => 0,
            'terms_summary' => 'Monthly or annual. Prices are placeholders pending review.',
            'limits' => [
                'maximum_active_runs'       => null,
                'maximum_service_categories' => null,
                'maximum_service_areas'     => null,
                'maximum_provider_users'    => 5,
                'maximum_branches'          => 3,
            ],
            'features' => [
                'can_create_service_run'            => true,
                'can_view_full_matching_requests'   => true,
                'can_access_advanced_statistics'    => true,
                'can_access_demand_reports'         => true,
                'can_be_featured'                   => true,
                'can_export_data'                   => true,
                'can_use_priority_matching'         => true,
                'can_create_caravan_park_service_days' => true,
                'can_use_custom_branding'           => true,
                'can_access_api'                    => false,
            ],
        ],
        [
            'slug'          => 'enterprise',
            'internal_name' => 'Enterprise / Multi-Branch Provider',
            'public_name'   => 'Enterprise',
            'description'   => 'Multiple branches and users, branch-level permissions, central administration, consolidated reporting, custom territories, API access, custom onboarding and an account manager. Negotiated pricing.',
            'monthly_price_cents' => 0,
            'annual_price_cents'  => 0,
            'trial_days'    => 0,
            'display_order' => 50,
            'is_active'     => 1,
            'is_public'     => 1,
            'signup_available' => 0,
            'is_recommended' => 0,
            'terms_summary' => 'Negotiated pricing — contact VanAssist.',
            'limits' => [
                'maximum_active_runs'       => null,
                'maximum_service_categories' => null,
                'maximum_service_areas'     => null,
                'maximum_provider_users'    => null,
                'maximum_branches'          => null,
            ],
            'features' => [
                'can_create_service_run'            => true,
                'can_view_full_matching_requests'   => true,
                'can_access_advanced_statistics'    => true,
                'can_access_demand_reports'         => true,
                'can_be_featured'                   => true,
                'can_export_data'                   => true,
                'can_use_priority_matching'         => true,
                'can_create_caravan_park_service_days' => true,
                'can_use_custom_branding'           => true,
                'can_access_api'                    => true,
            ],
        ],
    ],
];
