<?php

declare(strict_types=1);

$contact = '<a href="mailto:support@vanassist.com.au">support@vanassist.com.au</a>';

return [
    'privacy' => [
        'page_key' => 'privacy', 'slug' => 'privacy-policy', 'title' => 'Privacy policy',
        'body' => '<p><strong>Effective 28 July 2026.</strong> This policy explains how VanAssist, operated by Glen Condren (sole trader), ABN 76 553 821 887, collects, holds, uses and discloses personal information. We aim to handle personal information consistently with the Australian Privacy Principles and comply with the <em>Privacy Act 1988</em> (Cth) where it applies.</p>'
            . '<h2>What we collect</h2><p>Depending on how you use VanAssist, we may collect your name, email, phone number, account credentials, town or postcode, optional device location, caravan or vehicle details, service request details, provider business information, licences and insurance evidence, communications, consent records, saved listings, transaction records, and technical information such as IP address, browser, device, security logs and pages used.</p>'
            . '<h2>How we collect it</h2><p>We collect information directly from you, from people authorised by you, from providers and caravan parks, through website use, and from lawful public sources for clearly marked unclaimed business listings. If you provide information about another person, you must be authorised to do so.</p>'
            . '<h2>Why we use it</h2><p>We use information to operate accounts, locate and rank relevant services, process requests, connect users and providers, support service runs, verify provider evidence, respond to enquiries, prevent fraud and misuse, measure demand, improve coverage, comply with law, and send service messages. Marketing is sent only where permitted and can be stopped using the unsubscribe link or by contacting us.</p>'
            . '<h2>Location and automated matching</h2><p>Location access is optional. If allowed, coordinates are used to find nearby towns, stays and providers and to prepare map directions. Search ranking and matching may use automated rules such as service category, service area, distance, availability and verification. These tools assist discovery and do not make legal, credit, employment or insurance decisions. Provider verification and material account actions may involve human review.</p>'
            . '<h2>Who receives information</h2><p>We disclose information only as reasonably needed to providers you contact or ask us to match, authorised staff and contractors, hosting, email, security, analytics and payment providers, professional advisers, regulators and law enforcement where required, and a purchaser or successor if the business is transferred subject to appropriate safeguards. We do not sell personal information.</p>'
            . '<h2>Public and unclaimed listings</h2><p>Provider profiles may contain public business information. Unclaimed listings are identified as such and may be corrected, claimed or removed after appropriate verification. Personal service requests and customer contact details are not published as directory listings.</p>'
            . '<h2>Overseas processing</h2><p>Some technology providers may process or back up information outside Australia. Their locations can change. We take reasonable steps when selecting and managing providers and will provide further information about relevant providers on request where practicable.</p>'
            . '<h2>Security and retention</h2><p>We use access controls, encryption where appropriate, logging, backups and operational safeguards. No online system is risk free. We retain information only while needed for the purposes described, legitimate business records, dispute handling and legal obligations, then delete or de-identify it where reasonably practicable. Verification documents are restricted and should not be uploaded unless requested.</p>'
            . '<h2>Data breaches</h2><p>We assess suspected breaches and, where the Notifiable Data Breaches scheme applies, notify affected people and the Office of the Australian Information Commissioner when required.</p>'
            . '<h2>Access, correction and deletion</h2><p>You may request access to or correction of your personal information. You may also ask us to delete information, although legal, security, fraud-prevention and record-keeping obligations may require some information to be retained. We may need to verify your identity before acting.</p>'
            . '<h2>Children</h2><p>VanAssist is not directed to children under 18. A parent or guardian should contact us if they believe a child has provided personal information without appropriate authority.</p>'
            . '<h2>Cookies and external services</h2><p>Essential cookies support security, sessions and preferences. When first-party analytics are enabled, we use a randomly generated session identifier to count visits and understand page, search and provider-interest activity. Analytics reporting does not store visitor IP addresses or attempt to identify anonymous visitors; security logs may separately record technical information to protect the service. Optional advertising technologies will be used only as disclosed and subject to applicable consent choices. External maps, websites and payment services have their own privacy practices.</p>'
            . '<h2>Complaints and contact</h2><p>Contact ' . $contact . ' with privacy questions or complaints. We will acknowledge and investigate the matter within a reasonable time. If you are not satisfied, you may contact the <a href="https://www.oaic.gov.au" rel="nofollow noopener" target="_blank">Office of the Australian Information Commissioner</a>.</p>'
            . '<h2>Changes</h2><p>We may update this policy as the service or law changes. Material changes will be identified on this page and, where appropriate, notified directly.</p>',
    ],
    'terms' => [
        'page_key' => 'terms', 'slug' => 'terms-of-use', 'title' => 'Terms of use',
        'body' => '<p><strong>Effective 28 July 2026.</strong> These terms govern use of VanAssist, operated by Glen Condren (sole trader), ABN 76 553 821 887. By using the service you agree to them. If you use VanAssist for a business, you confirm you are authorised to bind that business.</p>'
            . '<h2>Platform role</h2><p>VanAssist is a directory, matching and coordination platform. Unless expressly stated, VanAssist is not the provider, customer, booking agent, insurer, engineer, mechanic, towing operator or caravan park. A quote, booking, service, payment, warranty and dispute is an arrangement between the user and provider.</p>'
            . '<h2>Eligibility and accounts</h2><p>You must be at least 18, provide accurate information, protect your account and promptly report unauthorised access. You are responsible for activity performed through your account unless caused by our failure to use reasonable care.</p>'
            . '<h2>Searches, location and maps</h2><p>Distances, opening information, availability, map results and service areas are estimates and may be incomplete. Confirm the address, route, access conditions and availability before travelling. Do not use the platform as an emergency navigation or safety service.</p>'
            . '<h2>Provider listings</h2><p>Providers are responsible for keeping claimed listings, qualifications, licences, insurance, services, prices and service areas accurate. Unclaimed listings use lawful public information and are clearly identified. A listing, verification badge, featured position or advertisement is not a guarantee or endorsement.</p>'
            . '<h2>User responsibilities</h2><p>Give accurate request and vehicle information, inspect provider suitability, obtain a written scope and price where appropriate, and follow safety and manufacturer guidance. Do not request unlawful work or rely on general platform information instead of professional advice.</p>'
            . '<h2>Provider responsibilities</h2><p>Providers must offer only services they are competent and legally permitted to perform, maintain required registrations and insurance, quote fairly, comply with consumer and safety laws, protect customer information, and avoid misleading claims, fake reviews or unsolicited marketing.</p>'
            . '<h2>Fees, promotions and advertising</h2><p>Any applicable fee, renewal, cancellation rule or sponsored placement will be shown before commitment. Sponsored results will be identified. Future pricing changes do not apply retrospectively to an agreed paid period. Statutory rights are not limited.</p>'
            . '<h2>Acceptable use</h2><p>You must not misuse accounts or personal information, scrape or copy the directory at scale, bypass security, introduce malicious code, impersonate another person, manipulate rankings or reviews, infringe rights, harass others, or use VanAssist unlawfully.</p>'
            . '<h2>Content and intellectual property</h2><p>You retain ownership of content you submit and grant VanAssist a non-exclusive licence to host, reproduce and display it only as needed to operate, promote and improve the service. You must have rights to submitted content. VanAssist branding, software and original content remain protected.</p>'
            . '<h2>Third-party services</h2><p>Maps, websites, payment services, official documents and other linked resources are controlled by third parties. Their terms apply separately. We do not control their availability or content.</p>'
            . '<h2>Suspension and removal</h2><p>We may restrict or remove content or access where reasonably necessary for security, unlawful conduct, material breach, substantiated risk, non-payment or protection of users. Where appropriate, we will give reasons and a reasonable opportunity to respond. You may stop using VanAssist at any time.</p>'
            . '<h2>Consumer guarantees</h2><p>Nothing in these terms excludes, restricts or modifies a guarantee, right or remedy that cannot lawfully be excluded, including under the Australian Consumer Law.</p>'
            . '<h2>Liability</h2><p>To the extent permitted by law, VanAssist is not liable for provider acts or omissions, user decisions, indirect loss, or information supplied by third parties. Where liability cannot be excluded but may lawfully be limited, it is limited to the remedies permitted by law. This clause is subject to the Consumer guarantees section.</p>'
            . '<h2>Changes and governing law</h2><p>We may update these terms for legal, security or service changes. Material changes will be notified reasonably before taking effect where practicable. Queensland law applies and courts with jurisdiction in Queensland may hear disputes, subject to rights that require another forum.</p>'
            . '<h2>Contact</h2><p>Questions or complaints can be sent to ' . $contact . '. If part of these terms is unenforceable, the remaining terms continue to apply.</p>',
    ],
    'disclaimer' => [
        'page_key' => 'disclaimer', 'slug' => 'disclaimer', 'title' => 'Disclaimer',
        'body' => '<p><strong>Effective 28 July 2026.</strong> VanAssist helps people discover and contact caravan, RV, vehicle and traveller services. Information is general and must be checked for your circumstances.</p>'
            . '<h2>Not an emergency service</h2><p>For immediate danger, injury, fire or another emergency call 000. Do not rely on VanAssist for emergency response, remote-area rescue, road closure warnings or real-time safety instructions.</p>'
            . '<h2>No professional advice</h2><p>Content is not mechanical, electrical, gas, engineering, legal, financial, insurance, roadworthiness or safety advice. Use appropriately qualified and licensed professionals and verify requirements with the relevant authority.</p>'
            . '<h2>Providers and listings</h2><p>VanAssist does not guarantee a provider, listing, licence, insurance, availability, price, response time, workmanship or fitness for a particular job. Verification means specified evidence was reviewed at a point in time, not that future work is guaranteed. Unclaimed listings may be incomplete or out of date.</p>'
            . '<h2>Regulatory and technical information</h2><p>Rules, standards and official documents can change and differ by vehicle, location and use. Check the current source issued by the responsible government, regulator, standards body, engineer or sanctioning organisation before acting.</p>'
            . '<h2>Weights, calculations and specifications</h2><p>Calculators and catalogue figures are planning aids. Results depend on accurate inputs and do not replace a weighbridge result, manufacturer specification, compliance plate, engineer assessment or legal limit. Allow for passengers, accessories, fluids, cargo and measurement uncertainty.</p>'
            . '<h2>Location, maps and travel information</h2><p>Distances may be straight-line estimates. Addresses, routes, fuel, stays, opening hours, access and road suitability may change. Confirm details directly and use current official travel and emergency information.</p>'
            . '<h2>Advertising and ranking</h2><p>Sponsored or featured placements are identified and do not amount to endorsement. Relevance and distance are considered separately from payment where stated.</p>'
            . '<h2>External content</h2><p>Links and embedded services are provided for convenience. VanAssist does not control third-party content, privacy, security or availability.</p>'
            . '<h2>Australian Consumer Law</h2><p>Nothing in this disclaimer excludes, restricts or modifies rights or remedies that cannot lawfully be excluded. Read this disclaimer with the Terms of use and Privacy policy.</p>'
            . '<h2>Corrections</h2><p>Report inaccurate or unsafe information to ' . $contact . ' so it can be reviewed.</p>',
    ],
];
