<?php
/** @var \App\Core\View $this */
$this->extend('layouts.admin');
?>
<?php $this->section('content'); ?>
<div class="admin-page-intro"><div><span class="eyebrow">Platform trust operations</span><h1>Rules, credentials and paid relevance</h1><p>Keep official sources current, review specialist evidence and approve commercial placements without allowing payment to influence authority or organic ranking.</p></div><form method="post" action="<?= e(url('admin/trust-growth/check-sources')) ?>"><?= csrf_field() ?><button class="btn btn-primary" type="submit">Check next 20 due sources</button></form></div>

<div class="metric-grid trust-metrics"><article class="card"><span>Public sources</span><strong><?= number_format($health['public']) ?></strong></article><article class="card"><span>Fail-closed review</span><strong><?= number_format($health['review']) ?></strong></article><article class="card"><span>Checks overdue</span><strong><?= number_format($health['overdue']) ?></strong></article><article class="card"><span>7-day failures</span><strong><?= number_format($health['failed']) ?></strong></article><article class="card"><span>Alert subscribers</span><strong><?= number_format($health['subscribers']) ?></strong></article></div>

<section class="card admin-trust-section"><div class="garage-section-heading"><div><span class="eyebrow">DATA-009</span><h2>Freshness and reviewer queue</h2></div><span class="badge badge-verified">Changed sources stay unpublished</span></div>
<div class="coverage-strip"><?php foreach ($coverage as $row): ?><div><strong><?= $this->e((string) $row['jurisdiction_code']) ?></strong><span><?= (int) $row['total'] ?> sources</span><small><?= (int) $row['review_count'] ?> review</small></div><?php endforeach; ?></div>
<div class="admin-review-list"><?php foreach ($reviewSources as $source): ?><article><div><span class="badge <?= $source['publication_status'] === 'review' ? 'badge-sponsored' : 'badge-neutral' ?>"><?= $this->e((string) $source['publication_status']) ?></span><h3><?= $this->e((string) $source['title']) ?></h3><p><?= $this->e((string) $source['authority_name']) ?> · checked <?= $this->e((string) ($source['last_checked_at'] ?: 'not yet')) ?></p><a href="<?= $this->e((string) $source['source_url']) ?>" target="_blank" rel="noopener noreferrer">Open official source</a></div><form method="post" action="<?= e(url('admin/trust-growth/source')) ?>"><?= csrf_field() ?><input type="hidden" name="document_id" value="<?= (int) $source['id'] ?>"><button class="btn btn-secondary btn-sm" name="review_action" value="confirm" type="submit">Confirm current</button><button class="btn btn-ghost btn-sm" name="review_action" value="retire" type="submit">Retire</button></form></article><?php endforeach; ?><?php if ($reviewSources === []): ?><p class="muted">No sources currently need attention.</p><?php endif; ?></div></section>

<div class="admin-trust-columns"><section class="card admin-trust-section"><span class="eyebrow">COM-006</span><h2>Capability evidence</h2><div class="admin-review-list"><?php foreach ($credentials as $credential): ?><article><div><h3><?= $this->e((string) $credential['business_name']) ?></h3><p><strong><?= $this->e((string) $credential['capability_label']) ?></strong> · <?= $this->e((string) ($credential['jurisdiction_code'] ?: 'Australia-wide')) ?></p><small>Evidence: <?= $this->e((string) ($credential['original_name'] ?: 'missing')) ?> · <?= $this->e((string) ($credential['evidence_status'] ?: 'unreviewed')) ?></small></div><form method="post" action="<?= e(url('admin/trust-growth/credential')) ?>"><?= csrf_field() ?><input type="hidden" name="credential_id" value="<?= (int) $credential['id'] ?>"><input type="text" name="review_notes" maxlength="500" placeholder="Review note"><button class="btn btn-secondary btn-sm" name="review_action" value="verify" type="submit">Verify</button><button class="btn btn-ghost btn-sm" name="review_action" value="reject" type="submit">Reject</button></form></article><?php endforeach; ?><?php if ($credentials === []): ?><p class="muted">No credential reviews waiting.</p><?php endif; ?></div></section>

<section class="card admin-trust-section"><span class="eyebrow">COM-007</span><h2>Campaign relevance review</h2><div class="admin-review-list"><?php foreach ($campaigns as $campaign): ?><article><div><h3><?= $this->e((string) $campaign['name']) ?></h3><p><?= $this->e((string) ($campaign['business_name'] ?: 'Platform advertiser')) ?> · <?= $this->e((string) $campaign['brand_name']) ?></p><small>$<?= number_format((int) $campaign['daily_budget_cents'] / 100, 2) ?>/day · $<?= number_format((int) $campaign['total_budget_cents'] / 100, 2) ?> total · <?= (int) $campaign['target_count'] ?> target</small><a href="<?= $this->e((string) $campaign['destination_url']) ?>" target="_blank" rel="noopener noreferrer">Inspect destination</a></div><form method="post" action="<?= e(url('admin/trust-growth/campaign')) ?>"><?= csrf_field() ?><input type="hidden" name="campaign_id" value="<?= (int) $campaign['id'] ?>"><label>Approved CPC (AUD)<input type="number" name="unit_price" min="0.10" max="100" step="0.01" required></label><button class="btn btn-secondary btn-sm" name="review_action" value="activate" type="submit">Activate</button><button class="btn btn-ghost btn-sm" name="review_action" value="reject" type="submit" formnovalidate>Reject</button></form></article><?php endforeach; ?><?php if ($campaigns === []): ?><p class="muted">No campaigns awaiting review.</p><?php endif; ?></div></section></div>

<section class="card admin-trust-section"><span class="eyebrow">Notification audit</span><h2>Recent source-change alerts</h2><div class="table-wrap"><table class="data"><thead><tr><th>Created</th><th>Source</th><th>Recipient</th><th>Status</th><th>Reason</th></tr></thead><tbody><?php foreach ($deliveries as $delivery): ?><tr><td><?= $this->e((string) $delivery['created_at']) ?></td><td><?= $this->e((string) $delivery['title']) ?></td><td><?= $this->e((string) $delivery['email']) ?></td><td><?= $this->e((string) $delivery['status']) ?></td><td><?= $this->e((string) ($delivery['reason'] ?: '—')) ?></td></tr><?php endforeach; ?><?php if ($deliveries === []): ?><tr><td colspan="5">No alerts queued yet.</td></tr><?php endif; ?></tbody></table></div></section>
<?php $this->endSection(); ?>
