<?php
$this->extend('layouts.public');
$errors = errors();
$field = static fn(string $key): string => (string) ($values[$key] ?? old($key, ''));
$labels = ['vehicle_gvm'=>'Vehicle GVM','vehicle_gcm'=>'Vehicle GCM','vehicle_max_braked_towing'=>'Maximum braked towing capacity','vehicle_max_towball'=>'Maximum towball download','vehicle_mass_before_ball'=>'Loaded vehicle mass before towball','trailer_atm'=>'Trailer ATM','trailer_loaded_mass'=>'Actual loaded trailer mass','towball_mass'=>'Actual towball mass'];
?>
<?php $this->section('content'); ?>
<section class="section"><div class="container" style="max-width:960px"><h1>Towing weight calculator</h1><p class="lead">Enter all values in kilograms. Use compliance plates and current loaded scale readings.</p>
<?php if (!empty($errors['calculator'])): ?><div class="alert alert-error" role="alert"><?= $this->e((string) $errors['calculator']) ?></div><?php endif; ?>
<form class="card" method="post" action="<?= e(url('calculator')) ?>"><?= csrf_field() ?><div class="grid grid-2"><?php foreach ($labels as $key=>$label): ?><div class="form-group"><label for="<?= e_attr($key) ?>"><?= $this->e($label) ?> (kg)</label><input id="<?= e_attr($key) ?>" name="<?= e_attr($key) ?>" type="number" min="0" step="0.1" required inputmode="decimal" value="<?= e_attr($field($key)) ?>"></div><?php endforeach; ?></div><button class="btn btn-primary btn-lg" type="submit">Calculate limits</button></form>
<?php if (!empty($result)): ?><section class="card" aria-labelledby="result-title" style="margin-top:1.5rem"><h2 id="result-title">Result: <?= $this->e(str_replace('_',' ',(string)$result['status'])) ?></h2><div class="table-wrap"><table class="data"><thead><tr><th>Check</th><th>Actual</th><th>Limit</th><th>Remaining</th><th>Status</th></tr></thead><tbody><?php foreach ($result['checks'] as $check): ?><tr><td><?= $this->e($check['label']) ?></td><td><?= $this->e((string)$check['actual']) ?> kg</td><td><?= $this->e((string)$check['limit']) ?> kg</td><td><?= $this->e((string)$check['remaining']) ?> kg</td><td><?= $this->e(str_replace('_',' ',$check['status'])) ?></td></tr><?php endforeach; ?></tbody></table></div><p><strong>Trailer GTM:</strong> <?= $this->e((string)$result['calculated']['trailer_gtm']) ?> kg · <strong>Combination mass:</strong> <?= $this->e((string)$result['calculated']['combination_mass']) ?> kg</p><div class="alert alert-info"><?= $this->e($result['disclaimer']) ?></div>
<?php if (auth()->check()): ?><form method="post" action="<?= e(url('account/towing-combinations')) ?>"><?= csrf_field() ?><?php foreach ($values as $key=>$value): ?><input type="hidden" name="<?= e_attr($key) ?>" value="<?= e_attr((string)$value) ?>"><?php endforeach; ?><div class="form-group"><label for="label">Combination name</label><input id="label" name="label" maxlength="150" value="My towing combination"></div><button class="btn btn-secondary" type="submit">Save this combination</button></form><?php else: ?><p><a href="<?= e(url('login')) ?>">Sign in</a> to save this result.</p><?php endif; ?></section><?php endif; ?></div></section>
<?php $this->endSection(); ?>
