<?php $this->extend('layouts.admin'); ?>
<?php $this->section('content'); ?>
<div class="page-header"><div><p class="eyebrow">Facility contribution #<?= (int)$contribution['id'] ?></p><h1><?= $this->e((string)$contribution['park_name']) ?></h1><p class="muted">Status: <?= $this->e(str_replace('_',' ',(string)$contribution['status'])) ?></p></div><a class="btn btn-ghost" href="<?= e(url('admin/facility-contributions')) ?>">Back to queue</a></div>
<div class="grid grid-2 admin-facility-compare"><section class="card"><h2>Current VanAssist data</h2><?php if($facilities===[]): ?><p class="muted">No structured facility facts.</p><?php else: ?><?php foreach($facilities as $fact): ?><p><strong><?= $this->e((string)$fact['label']) ?>:</strong> <?= $this->e((string)$fact['display']) ?><br><small><?= $this->e((string)$fact['source_name']) ?> · <?= $this->e((string)($fact['verified_at']??$fact['last_seen_at']??'Not dated')) ?></small></p><?php endforeach; ?><?php endif; ?></section>
<section class="card"><h2>User suggestion</h2><?php if($contribution['comment']): ?><p><?= nl2br($this->e((string)$contribution['comment'])) ?></p><?php endif; ?><?php if($contribution['evidence_url']): ?><p><a href="<?= e_attr((string)$contribution['evidence_url']) ?>" target="_blank" rel="noopener noreferrer">Open supporting source</a></p><?php endif; ?></section></div>
<?php if(count($claims)>count($facilities)): ?><details class="card"><summary>Conflicting and lower-priority source claims</summary><?php foreach($claims as $claim): ?><p><strong><?= $this->e(\App\Services\StayFacilityService::TYPES[$claim['facility_type']]??$claim['facility_type']) ?>:</strong> <?= $this->e((string)$claim['facility_status']) ?><?= $claim['facility_value']?' · '.$this->e((string)$claim['facility_value']):'' ?> — <?= $this->e((string)$claim['source_name']) ?> (confidence <?= (int)$claim['source_confidence'] ?>)</p><?php endforeach; ?></details><?php endif; ?>
<?php if(in_array($contribution['status'],['pending','under_review'],true)): ?><form method="post" action="<?= e(url('admin/facility-contributions/moderate')) ?>" class="card stack"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$contribution['id'] ?>"><h2>Review items</h2><?php foreach($items as $item): ?><fieldset class="facility-review-item"><legend><?= $this->e(\App\Services\StayFacilityService::TYPES[$item['facility_type']]??$item['facility_type']) ?></legend><label><input type="checkbox" name="item[<?= (int)$item['id'] ?>][approve]" value="1" checked> Approve this item</label><div class="grid grid-2"><label>Status<select name="item[<?= (int)$item['id'] ?>][status]"><?php foreach(['yes','no','conditional','unknown'] as $s): ?><option value="<?= $s ?>" <?= $item['suggested_status']===$s?'selected':'' ?>><?= ucfirst($s) ?></option><?php endforeach; ?></select></label><label>Value<input name="item[<?= (int)$item['id'] ?>][value]" value="<?= e_attr((string)$item['suggested_value']) ?>"></label></div><label>Details<textarea name="item[<?= (int)$item['id'] ?>][details]" rows="3"><?= $this->e((string)$item['suggested_details']) ?></textarea></label><p class="muted">Previous: <?= $this->e((string)($item['existing_status']??'not listed')) ?> · Suggested: <?= $this->e((string)$item['suggested_status']) ?></p></fieldset><?php endforeach; ?><label>Moderator notes<textarea name="notes" maxlength="2000" rows="3"></textarea></label><div class="actions"><button class="btn btn-primary" name="action" value="approve">Approve</button><button class="btn btn-secondary" name="action" value="approve_edit">Approve with edits</button><button class="btn btn-secondary" name="action" value="partial">Partially approve</button><button class="btn btn-ghost" name="action" value="reject">Reject</button><button class="btn btn-ghost" name="action" value="duplicate">Mark duplicate</button></div></form><?php endif; ?>
<?php if($history!==[]): ?><section class="card"><h2>Moderation history</h2><?php foreach($history as $entry): ?><p><strong><?= $this->e((string)$entry['action']) ?></strong> by <?= $this->e((string)($entry['moderator_name']??'administrator')) ?> · <?= $this->e((string)$entry['created_at']) ?></p><?php endforeach; ?></section><?php endif; ?>
<?php $this->endSection(); ?>
