CREATE TABLE trailer_listings (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    brand_id INT UNSIGNED NOT NULL DEFAULT 3,
    provider_id INT UNSIGNED NOT NULL,
    slug VARCHAR(200) NOT NULL,
    title VARCHAR(190) NOT NULL,
    listing_type ENUM('new','used','hire') NOT NULL DEFAULT 'used',
    trailer_type ENUM('box','car','boat','camper','caravan','horse_float','plant','tipper','commercial','other') NOT NULL DEFAULT 'other',
    description TEXT NOT NULL,
    make VARCHAR(100) NULL,
    model VARCHAR(100) NULL,
    model_year SMALLINT UNSIGNED NULL,
    price_aud DECIMAL(12,2) NULL,
    atm_kg DECIMAL(8,1) NULL,
    tare_kg DECIMAL(8,1) NULL,
    location_text VARCHAR(190) NULL,
    status ENUM('draft','pending','active','sold','suspended','archived') NOT NULL DEFAULT 'pending',
    is_featured TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_trailer_listing_slug (brand_id, slug),
    KEY idx_trailer_listing_market (brand_id, status, trailer_type, listing_type, deleted_at),
    KEY idx_trailer_listing_provider (provider_id, status),
    CONSTRAINT fk_trailer_listing_brand FOREIGN KEY (brand_id) REFERENCES brands (id) ON DELETE RESTRICT,
    CONSTRAINT fk_trailer_listing_provider FOREIGN KEY (provider_id) REFERENCES providers (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
