-- Public caravan-park, campground and low-cost stay directory for VanAssist.
ALTER TABLE caravan_parks
    ADD COLUMN stay_type ENUM('caravan_park','campground','free_camp','showground','rest_area','farm_stay','other') NOT NULL DEFAULT 'caravan_park' AFTER description,
    ADD COLUMN price_type ENUM('free','donation','low_cost','paid','unknown') NOT NULL DEFAULT 'unknown' AFTER stay_type,
    ADD COLUMN latitude DECIMAL(10,7) NULL AFTER state_id,
    ADD COLUMN longitude DECIMAL(10,7) NULL AFTER latitude,
    ADD COLUMN booking_url VARCHAR(500) NULL AFTER website,
    ADD COLUMN powered_sites TINYINT(1) NULL AFTER number_of_sites,
    ADD COLUMN unpowered_sites TINYINT(1) NULL AFTER powered_sites,
    ADD COLUMN toilets TINYINT(1) NULL AFTER unpowered_sites,
    ADD COLUMN showers TINYINT(1) NULL AFTER toilets,
    ADD COLUMN potable_water TINYINT(1) NULL AFTER showers,
    ADD COLUMN dump_point TINYINT(1) NULL AFTER potable_water,
    ADD COLUMN pets_allowed TINYINT(1) NULL AFTER dump_point,
    ADD COLUMN max_stay VARCHAR(80) NULL AFTER pets_allowed,
    ADD COLUMN source_type VARCHAR(40) NULL AFTER max_stay,
    ADD COLUMN source_url VARCHAR(500) NULL AFTER source_type,
    ADD COLUMN external_id VARCHAR(100) NULL AFTER source_url,
    ADD COLUMN source_checked_at DATETIME NULL AFTER external_id,
    ADD COLUMN verification_type ENUM('unverified','community','authority','operator') NOT NULL DEFAULT 'unverified' AFTER source_checked_at,
    ADD COLUMN verified_at DATETIME NULL AFTER source_checked_at,
    ADD COLUMN listing_plan ENUM('free','verified','premium','featured') NOT NULL DEFAULT 'free' AFTER verified_at,
    ADD COLUMN subscription_status ENUM('none','trial','active','past_due','cancelled') NOT NULL DEFAULT 'none' AFTER listing_plan,
    ADD COLUMN is_featured TINYINT(1) NOT NULL DEFAULT 0 AFTER public_page_enabled,
    ADD COLUMN sponsored_until DATETIME NULL AFTER is_featured,
    ADD UNIQUE KEY uq_caravan_parks_source (source_type, external_id),
    ADD KEY idx_caravan_parks_geo (latitude, longitude),
    ADD KEY idx_caravan_parks_directory (status, public_page_enabled, stay_type, price_type),
    ADD KEY idx_caravan_parks_featured (is_featured, sponsored_until);

CREATE TABLE caravan_park_claims (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    park_id INT UNSIGNED NOT NULL,
    claimant_name VARCHAR(150) NOT NULL,
    claimant_email VARCHAR(190) NOT NULL,
    claimant_phone VARCHAR(40) NULL,
    relationship_to_park VARCHAR(120) NULL,
    evidence_notes TEXT NULL,
    status ENUM('pending','approved','rejected','withdrawn') NOT NULL DEFAULT 'pending',
    reviewed_by INT UNSIGNED NULL,
    reviewed_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NULL,
    PRIMARY KEY (id),
    KEY idx_park_claim_status (status, created_at),
    KEY idx_park_claim_park (park_id),
    CONSTRAINT fk_park_claim_park FOREIGN KEY (park_id) REFERENCES caravan_parks (id) ON DELETE CASCADE,
    CONSTRAINT fk_park_claim_reviewer FOREIGN KEY (reviewed_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
