-- Private, evidence-gated review workflow for caravan-stay discovery packs.
-- Discovery rows never become public listings automatically.

CREATE TABLE caravan_stay_import_jobs (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    brand_id INT UNSIGNED NOT NULL,
    original_name VARCHAR(190) NOT NULL,
    staged_file VARCHAR(190) NULL,
    status ENUM('queued','running','review','failed','cancelled') NOT NULL DEFAULT 'queued',
    processed_lines INT UNSIGNED NOT NULL DEFAULT 0,
    candidates_new INT UNSIGNED NOT NULL DEFAULT 0,
    skipped_lines INT UNSIGNED NOT NULL DEFAULT 0,
    errors_json JSON NULL,
    requested_by INT UNSIGNED NULL,
    started_at DATETIME NULL,
    completed_at DATETIME NULL,
    expires_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_stay_import_jobs_brand (brand_id, status, created_at),
    KEY idx_stay_import_jobs_expiry (status, expires_at),
    CONSTRAINT fk_stay_import_job_brand FOREIGN KEY (brand_id) REFERENCES brands (id) ON DELETE CASCADE,
    CONSTRAINT fk_stay_import_job_user FOREIGN KEY (requested_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE caravan_stay_import_candidates (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    job_id INT UNSIGNED NOT NULL,
    brand_id INT UNSIGNED NOT NULL,
    external_id VARCHAR(255) NOT NULL,
    name VARCHAR(190) NOT NULL,
    address VARCHAR(255) NULL,
    phone VARCHAR(40) NULL,
    website VARCHAR(500) NULL,
    latitude DECIMAL(10,7) NULL,
    longitude DECIMAL(10,7) NULL,
    candidate_state CHAR(3) NULL,
    stay_type ENUM('caravan_park','campground','free_camp','national_park','showground','rest_area','council_camp','farm_stay','station_stay','other') NOT NULL DEFAULT 'other',
    price_type ENUM('free','donation','low_cost','paid','unknown') NOT NULL DEFAULT 'unknown',
    business_status VARCHAR(40) NULL,
    route_hubs_json JSON NULL,
    raw_json JSON NOT NULL,
    review_status ENUM('pending','held','approved','merged','rejected') NOT NULL DEFAULT 'pending',
    hold_reason VARCHAR(500) NULL,
    duplicate_park_id INT UNSIGNED NULL,
    duplicate_score TINYINT UNSIGNED NOT NULL DEFAULT 0,
    evidence_url VARCHAR(500) NULL,
    review_notes VARCHAR(1000) NULL,
    park_id INT UNSIGNED NULL,
    reviewed_by INT UNSIGNED NULL,
    reviewed_at DATETIME NULL,
    expires_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_stay_import_candidate (brand_id, external_id),
    KEY idx_stay_import_review (brand_id, review_status, stay_type, candidate_state),
    KEY idx_stay_import_duplicate (brand_id, duplicate_park_id, review_status),
    KEY idx_stay_import_expiry (expires_at),
    CONSTRAINT fk_stay_import_candidate_job FOREIGN KEY (job_id) REFERENCES caravan_stay_import_jobs (id) ON DELETE CASCADE,
    CONSTRAINT fk_stay_import_candidate_brand FOREIGN KEY (brand_id) REFERENCES brands (id) ON DELETE CASCADE,
    CONSTRAINT fk_stay_import_candidate_duplicate FOREIGN KEY (duplicate_park_id) REFERENCES caravan_parks (id) ON DELETE SET NULL,
    CONSTRAINT fk_stay_import_candidate_park FOREIGN KEY (park_id) REFERENCES caravan_parks (id) ON DELETE SET NULL,
    CONSTRAINT fk_stay_import_candidate_reviewer FOREIGN KEY (reviewed_by) REFERENCES users (id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
