<?php

declare(strict_types=1);

return [
    'towsmart' => [
        'public-weighing' => ['weighbridge', 'mobile weighing', 'vehicle weighing', 'caravan weighing'],
        'towing-training' => ['towing training', 'caravan training', 'trailer training'],
        'towbars-hitches' => ['towbar', 'tow bar', 'hitch', 'coupling', 'weight distribution'],
        'brakes-controllers' => ['brake controller', 'trailer brake', 'electric brake', 'breakaway'],
        'suspension-payload' => ['suspension', 'payload', 'gvm upgrade', 'load assist'],
        'towing-electrical' => ['auto electrician', 'auto electrical', 'trailer wiring', '12v', '12 volt'],
        'tyres-wheels' => ['tyre', 'tire', 'wheel alignment', 'wheel service'],
        'towing-inspections' => ['roadworthy', 'safety certificate', 'inspection station', 'trailer inspection'],
    ],
    'trailerwise' => [
        'trailer-repairs' => ['trailer repair', 'trailer service', 'trailer servicing'],
        'roadworthy-inspections' => ['roadworthy', 'safety certificate', 'inspection station', 'pink slip', 'blue slip', 'trailer inspection'],
        'tyres-wheels-bearings' => ['tyre', 'tire', 'wheel', 'bearing', 'hub'],
        'brakes-axles-suspension' => ['trailer brake', 'brake controller', 'axle', 'suspension', 'spring'],
        'auto-electrical' => ['auto electrician', 'auto electrical', 'trailer wiring', 'trailer lighting', '12v', '12 volt'],
        'fabrication-engineering' => ['trailer fabrication', 'trailer engineering', 'welder', 'welding', 'chassis'],
        'parts-accessories' => ['trailer parts', 'trailer accessories', 'coupling', 'jockey wheel'],
        'manufacturers-dealers' => ['trailer manufacturer', 'trailer builder', 'trailer dealer', 'trailers'],
        'mobile-trailer-services' => ['mobile trailer', 'mobile mechanic', 'mobile welder', 'roadside trailer'],
    ],
    'localtorque' => [
        'mechanics' => ['mechanic', 'mechanical repair', 'car service', 'automotive service', 'workshop'],
        'mobile-mechanics' => ['mobile mechanic', 'mobile automotive', 'on-site mechanic'],
        'auto-electricians' => ['auto electrician', 'auto electrical', 'automotive electrical'],
        'diesel-specialists' => ['diesel mechanic', 'diesel specialist', 'diesel service'],
        'brake-clutch' => ['brake', 'clutch'],
        'suspension' => ['suspension', 'shock absorber'],
        'steering' => ['steering', 'power steering'],
        'tyre-shops' => ['tyre', 'tire', 'puncture', 'bob jane', 'beaurepaires'],
        'wheel-alignment' => ['wheel alignment', 'wheel balancing'],
        'windscreens' => ['windscreen', 'auto glass', 'automotive glass'],
        'air-conditioning' => ['auto air conditioning', 'automotive air conditioning', 'vehicle air conditioning'],
        'radiator-specialists' => ['radiator', 'cooling system'],
        'exhaust-shops' => ['exhaust', 'muffler'],
        'performance-workshops' => ['performance workshop', 'performance automotive'],
        'dyno-tuners' => ['dyno', 'dynamometer'],
        'transmission-specialists' => ['transmission', 'automatic gearbox', 'gearbox repair'],
        'differential-specialists' => ['differential', 'diff specialist'],
        'engine-rebuilders' => ['engine rebuild', 'engine recondition', 'engine machining'],
        'ecu-tuning' => ['ecu tuning', 'ecu remap', 'engine tuning'],
        'caravan-repairs' => ['caravan repair', 'caravan service', 'rv repair'],
        'trailer-repairs' => ['trailer repair', 'trailer service'],
        'fabrication' => ['fabrication', 'fabricator'],
        'welding' => ['welder', 'welding'],
        'panel-beaters' => ['panel beater', 'collision repair', 'smash repair'],
        'paint-shops' => ['auto paint', 'automotive paint', 'vehicle refinishing', 'spray painter'],
        'detailers' => ['car detail', 'vehicle detail', 'automotive detailing'],
        'rust-repairs' => ['rust repair', 'rust treatment'],
        'four-wheel-drive-specialists' => ['4wd', 'four wheel drive', 'off road vehicle'],
        'suspension-lift-specialists' => ['suspension lift', 'lift kit'],
        'bullbar-installation' => ['bullbar', 'bull bar'],
        'canopy-installation' => ['ute canopy', 'canopy installation'],
        'accessory-installers' => ['accessory installer', 'vehicle accessories', 'automotive accessories'],
        'battery-specialists' => ['battery specialist', 'car battery', 'vehicle battery'],
        'auto-locksmiths' => ['auto locksmith', 'automotive locksmith', 'car keys'],
        'vehicle-inspections' => ['vehicle inspection', 'pre-purchase inspection'],
        'roadworthy-inspections' => ['roadworthy', 'safety certificate', 'inspection station', 'pink slip', 'blue slip'],
        'fleet-maintenance' => ['fleet maintenance', 'fleet servicing', 'fleet service'],
        'agricultural-machinery' => ['agricultural machinery', 'farm machinery', 'tractor repair'],
        'marine-mechanics' => ['marine mechanic', 'boat mechanic', 'marine engine'],
        'motorcycle-workshops' => ['motorcycle workshop', 'motorbike mechanic', 'motorcycle mechanic'],
    ],
];

