<?php
/** @var \App\Core\View $this */
$this->extend('layouts.public');
$brandName = current_brand()->name();
?>
<?php $this->section('content'); ?>
<section class="brand-provider-hero"><div class="container"><p class="experience-kicker">Assist Platform for <?= $this->e($brandName) ?> businesses</p><h1>One credible business presence.<br><em>More relevant ways to be found.</em></h1><p>Manage your business details once, participate only in relevant brands, and make it clearer for customers to understand what you do and where you operate.</p><div><a class="btn btn-light btn-lg" href="<?= e(url('for-providers/register')) ?>">Register your business</a><a class="btn btn-glass btn-lg" href="#business-value">See how it works</a></div></div></section>
<section class="section" id="business-value"><div class="container"><div class="editorial-heading"><p class="experience-kicker dark">Built around useful business outcomes</p><h2>Presence, trust and demand in one provider account.</h2></div><div class="journey-grid"><article class="journey-card"><span class="journey-number">01</span><div><p>Discovery</p><h3>Be found for relevant work</h3><span>Connect services, locations and brand relevance without duplicated listings.</span></div></article><article class="journey-card"><span class="journey-number">02</span><div><p>Control</p><h3>Maintain accurate information</h3><span>Manage public details, coverage, credentials and availability.</span></div></article><article class="journey-card"><span class="journey-number">03</span><div><p>Insight</p><h3>Understand genuine interest</h3><span>Separate searches and contact activity from confirmed outcomes.</span></div></article></div></div></section>
<section class="section section-ink"><div class="container split-feature"><div><p class="experience-kicker">Honest marketplace participation</p><h2>No hidden commitment at registration.</h2><p>Registering interest does not start billing, guarantee leads or require the business to accept work. Verification and promotional visibility remain clearly labelled.</p></div><a class="btn btn-light btn-lg" href="<?= e(url('for-providers/register')) ?>">Register with <?= $this->e($brandName) ?></a></div></section>
<?php $this->endSection(); ?>
