<?php
/** @var \App\Core\View $this */
/** @var array<string,mixed> $report */
$this->extend('layouts.admin');
$facilities = $report['facility_summary'];
$trust = $report['provider_trust'];
?>
<?php $this->section('content'); ?>
<div class="admin-page-intro">
    <div><p class="eyebrow">VanAssist operating loop</p><h1>Growth and trust</h1><p class="muted">Publish reliable coverage, fix real search failures, verify providers and expand regional pages only when local evidence supports them.</p></div>
    <a class="btn btn-ghost" href="<?= e(url('admin/demand')) ?>">Website insights</a>
</div>
<section class="card" aria-labelledby="facility-coverage-heading">
    <div class="admin-section-heading"><div><p class="eyebrow">Facility publication</p><h2 id="facility-coverage-heading">From acquired data to searchable records</h2></div><a class="btn btn-ghost btn-sm" href="<?= e(url('admin/data-sources/facilities/review')) ?>">Review candidates</a></div>
    <div class="insight-stat-grid"><?php foreach ([['Published',$facilities['published'],'Reviewed or verified'],['Searchable',$facilities['searchable'],'Published with coordinates'],['Verified',$facilities['verified'],'Evidence independently verified'],['Awaiting review',$facilities['pending_candidates'],'Not public'],['Active datasets',$facilities['active_datasets'],'Approved acquisition sources']] as [$label,$value,$hint]): ?><article class="insight-stat"><strong><?= number_format((int)$value) ?></strong><span><?= $this->e($label) ?></span><small><?= $this->e($hint) ?></small></article><?php endforeach; ?></div>
    <div class="insight-grid insight-grid--two">
        <div class="table-wrap"><table class="data data--compact"><caption>Coverage by facility type</caption><thead><tr><th>Type</th><th>Published</th><th>Searchable</th><th>Verified</th></tr></thead><tbody><?php foreach($report['facility_types'] as $row): ?><tr><td><?= $this->e(ucwords(str_replace('_',' ',(string)$row['label']))) ?></td><td><?= number_format((int)$row['published']) ?></td><td><?= number_format((int)$row['searchable']) ?></td><td><?= number_format((int)$row['verified']) ?></td></tr><?php endforeach; ?><?php if($report['facility_types']===[]): ?><tr><td colspan="4" class="muted">No published facilities.</td></tr><?php endif; ?></tbody></table></div>
        <div class="table-wrap"><table class="data data--compact"><caption>Coverage by state</caption><thead><tr><th>State</th><th>Published</th><th>Types</th><th>Searchable</th></tr></thead><tbody><?php foreach($report['facility_states'] as $row): ?><tr><td><?= $this->e((string)$row['label']) ?></td><td><?= number_format((int)$row['published']) ?></td><td><?= number_format((int)$row['types']) ?></td><td><?= number_format((int)$row['searchable']) ?></td></tr><?php endforeach; ?></tbody></table></div>
    </div>
</section>
<section class="card" aria-labelledby="search-loop-heading">
    <div class="admin-section-heading"><div><p class="eyebrow">Search-success loop</p><h2 id="search-loop-heading">Highest-priority unmet searches</h2><p class="muted">Research repeated failures, publish evidence, then resolve the linked gap. Clicks and contacts are usefulness signals—not completed jobs.</p></div><a class="btn btn-ghost btn-sm" href="<?= e(url('admin/ai-search/gaps')) ?>">Manage all gaps</a></div>
    <div class="table-wrap"><table class="data"><thead><tr><th>What was requested</th><th>Location</th><th>Searches</th><th>Zero results</th><th>Useful actions</th><th>Priority</th></tr></thead><tbody><?php foreach($report['search_priorities'] as $row): ?><tr><td><strong><?= $this->e((string)$row['query_sample']) ?></strong><small><?= $this->e(ucwords(str_replace('_',' ',(string)$row['intent_type']))) ?></small></td><td><?= $this->e((string)$row['location_name']) ?></td><td><?= number_format((int)$row['search_count']) ?></td><td><?= number_format((int)$row['zero_result_count']) ?></td><td><?= number_format((int)$row['click_through_count']+(int)$row['contact_action_count']) ?></td><td><strong><?= number_format((int)$row['priority_score']) ?></strong></td></tr><?php endforeach; ?><?php if($report['search_priorities']===[]): ?><tr><td colspan="6" class="muted">No open search gaps.</td></tr><?php endif; ?></tbody></table></div>
</section>
<section class="card" aria-labelledby="provider-trust-heading">
    <div class="admin-section-heading"><div><p class="eyebrow">Provider verification and value</p><h2 id="provider-trust-heading">Trust pipeline</h2></div><div class="btn-row"><a class="btn btn-ghost btn-sm" href="<?= e(url('admin/providers')) ?>">Review providers</a><a class="btn btn-ghost btn-sm" href="<?= e(url('admin/demand/providers')) ?>">Provider value report</a></div></div>
    <div class="insight-stat-grid"><?php foreach ([['Active listings',$trust['active'],'Visible for VanAssist'],['Claimed',$trust['claimed'],'Provider-controlled'],['Evidence verified',$trust['verified'],'Basis, notes and reviewer recorded'],['Claims awaiting review',$trust['pending_claims'],'Needs an authority decision'],['More evidence requested',$trust['evidence_requested'],'No control granted']] as [$label,$value,$hint]): ?><article class="insight-stat"><strong><?= number_format((int)$value) ?></strong><span><?= $this->e($label) ?></span><small><?= $this->e($hint) ?></small></article><?php endforeach; ?></div>
</section>
<section class="card" aria-labelledby="seo-heading">
    <div class="admin-section-heading"><div><p class="eyebrow">Regional SEO</p><h2 id="seo-heading">Evidence-backed town candidates</h2><p class="muted">A town becomes indexable only after reviewed copy, SEO metadata and at least three live local records. This prevents thin generated pages.</p></div><a class="btn btn-ghost btn-sm" href="<?= e(url('admin/locations/towns')) ?>">Edit town content</a></div>
    <div class="table-wrap"><table class="data"><thead><tr><th>Town</th><th>Providers</th><th>Facilities</th><th>Stays</th><th>90-day searches</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($report['seo_candidates'] as $row): ?><tr><td><strong><?= $this->e((string)$row['name'].', '.(string)$row['state_abbr']) ?></strong><small>/towns/<?= $this->e((string)$row['slug']) ?></small></td><td><?= number_format((int)$row['providers']) ?></td><td><?= number_format((int)$row['facilities']) ?></td><td><?= number_format((int)$row['stays']) ?></td><td><?= number_format((int)$row['searches']) ?></td><td><?php if(!empty($row['eligible'])): ?><span class="badge badge-success">Ready for review</span><?php else: ?><span class="muted"><?= $this->e((string)$row['blocker']) ?></span><?php endif; ?></td><td><?php if(!empty($row['eligible']) && can('seo.manage')): ?><form method="post" action="<?= e(url('admin/growth-trust/publish-town')) ?>"><?= csrf_field() ?><input type="hidden" name="town_id" value="<?= (int)$row['id'] ?>"><button class="btn btn-primary btn-sm" type="submit">Publish page</button></form><?php endif; ?></td></tr><?php endforeach; ?><?php if($report['seo_candidates']===[]): ?><tr><td colspan="7" class="muted">No noindex town candidates remain.</td></tr><?php endif; ?></tbody></table></div>
</section>
<?php $this->endSection(); ?>
